### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by aslafy-z** [webdevops/azure-k8s-autopilot#2]
I'd love to use this project for my infrastructure. Seeing that there were no updates since last year, do you still use it? Will you continue maintaining it? I would love to contribute on it if I find anything to do.

**Comment by mblaschke** [comment]
Hm.. currently my company switched from our custom clusters to AKS so there is currently no need.
For what kind of clusters do you use the autopilot? And what features are you using?

**Comment by aslafy-z** [comment]
I use it on custom clusters using VMSSs. I'm only using the Update (+drain) feature at this time.

**Comment by mblaschke** [comment]
just published 21.11.0.. i'm trying to publish new versions in future
