### ISSUE TITLE
Crashes on API server timeout

### ISSUE THREAD

**Issue by aslafy-z** [webdevops/azure-k8s-autopilot#3]
When the API server is not reachable (timeout) for any reason, this controller crashes. It's then restarted and will resume its work, so it's not a critical issue. I think some work can be done to retry with backoff instead of crashing. I'll post some logs in there when I reproduce the issue.

**Comment by mblaschke** [comment]
are you running them on master nodes? and are communicating to themselves?
if yes, there is a `1/${MasterNodeCount}` probability that the connection runs in a timeout if you connect from a VMSS to a loadblanacer which is attached to the same VMSS.

Azure LoadBalancers in azure drop traffic if it would hit the same VM where it came from (to prevent loops).

**Comment by aslafy-z** [comment]
I was not able to reproduce the issue. The pods where not scheduled on the leaders and anyway I'm using RKE which does not support using an external load balancer in front of the leaders (it configures a local nginx-proxy on each worker with the list of the leaders). I'll reopen this issue if needed in the future. Thank you!
