### ISSUE TITLE
Add option to drain with disable eviction if drain fails

### ISSUE THREAD

**Issue by aslafy-z** [webdevops/azure-k8s-autopilot#5]
When PDBs are wrongly configured, drain can fail and cause pods to block the node upgrade. 
Add an option that retries the drain with --disable-eviction if the first 'classic' one failed after a timeout.

Relates to https://github.com/webdevops/azure-k8s-autopilot/issues/6
See https://github.com/kubernetes/kubernetes/issues/83307#issuecomment-560413975

**Comment by mblaschke** [comment]
thanks, merged and released :)

**Comment by aslafy-z** [comment]
@mblaschke this issue is about an other feature:
- try first to drain with eviction
- if it fails, drain with disable eviction mode

**Comment by mblaschke** [comment]
i've added env `DRAIN_RETRY_WITHOUT_EVICTION` and `DRAIN_IGNORE_FAILURE`, can you try this solution?

**Comment by mblaschke** [comment]
Also the `:main` now includes the new azure-sdk-for-go

**Comment by aslafy-z** [comment]
Thank you @mblaschke for the quick implementation! From the description, it matches the requested feature. I'll get ahead and close this issue. We'll try this ASAP and get back to you.
